name: dcc_task_management
description: "DCC Task Management Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  riverpod: ^2.5.1
  freezed: ^2.4.7
  freezed_annotation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.0.7

flutter:
  uses-material-design: true
